FROM svgitlab.spatialvision.com.au:4567/GROUP/YOUR_PROJECT:base

WORKDIR /usr/app

RUN npm install -g supervisor mocha

COPY package.json .
RUN npm install --quiet

# expose proxy port
EXPOSE 3000
CMD [ "npm", "start" ]

